#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 Ayumu Saito
# SPDX-License-Identifier: BSD-3-Clause

def get_score(grade):
    if grade == 'S':
        return 4
    if grade == 'A':
        return 3
    if grade == 'B':
        return 2
    if grade == 'C':
        return 1
    if grade == 'D':
        return 0
    else:
        return None

