#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2025 Ayumu Saito
# SPDX-License-Identifier: BSD-3-Clause

def get_score(grade):
    if grade == 'S':
        return 4
    if grade == 'A':
        return 3
    if grade == 'B':
        return 2
    if grade == 'C':
        return 1
    if grade == 'D':
        return 0
    else:
        return None

grades_input = input("成績を空白で区切ってください")
grades = grades_input.split()

total = 0
count =0

for grade in grades:
    scoer = get_score(grade)
    if score is not None
    total +=score
    count += 1

if count >= 0:
    gpa = total / count
else:
